# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countPrincipalDownSets <- function(left, right) {
    .Call(`_rankUncertainty_countPrincipalDownSets`, left, right)
}

getCompatibility <- function(ranking, left, right) {
    .Call(`_rankUncertainty_getCompatibility`, ranking, left, right)
}

getIndexIntervals <- function(left, right) {
    .Call(`_rankUncertainty_getIndexIntervals`, left, right)
}

getPartitionInfo <- function(indices, idxLeft, idxRight) {
    .Call(`_rankUncertainty_getPartitionInfo`, indices, idxLeft, idxRight)
}

makeCanonicalRep <- function(indices, left, right) {
    .Call(`_rankUncertainty_makeCanonicalRep`, indices, left, right)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rankUncertainty_RcppExport_registerCCallable', PACKAGE = 'rankUncertainty')
})
